-- EXECUTE THE ADD CUSTOMER PROCEDURE
EXECUTE CITI_BANK.ADD_CUSTOMER('JAMES','S','MILLER','M','01-JUN-2018','IND');
SELECT * FROM BANK_CUST;

-- EXECUTE THE ADD_CUST_CONTACT PROCEDURE
EXECUTE CITI_BANK.ADD_CUSTOMER_CONTACT(1011,9885000935,'HOME','56 RD NO 14 B HILLS','BNR COLONY','HYD','TS',500034);
SELECT * FROM BANK_CUST_CONTACT;

-- EXECUTE THE ADD_SB_ACCOUNT PROCEDURE
EXECUTE CITI_BANK.ADD_SAVINGBANK_ACCOUNT(1011,NULL,1000,'ACTIVE',SYSDATE,NULL);
SELECT * FROM BANK_SB_ACCOUNT;
SELECT * FROM BANK_TRANSACTION;

-- EXECUTE THE SB_DEPOSIT PROCEDURE
EXECUTE CITI_BANK.SAVINGBANK_DEPOSIT (1000012011,'Deposit',1000);
SELECT * FROM BANK_SB_ACCOUNT;
SELECT * FROM BANK_TRANSACTION;

-- EXECUTE THE SB_DEPOSIT WITHDRAW PROCEDURE
EXECUTE CITI_BANK.SAVINGBANK_WITHDRAW(1000012011,'Withdrawal',1000);
SELECT * FROM BANK_SB_ACCOUNT;
SELECT * FROM BANK_TRANSACTION;

-- EXEC THE DEL_CUST PROCEDURE (IT IS OVERLOADED PROCEDURE)
EXECUTE CITI_BANK.DEL_CUSTOMER('john');
SELECT * FROM BANK_INT_RATE;
SELECT * FROM BANK_TRANSACTION;
