					       -----------------------------------------
						-- PACKAGE SPECIFICATION FOR BANK_PACK
                                               ------------------------------------------
CREATE OR REPLACE PACKAGE CITI_BANK IS
-- PROCEDURE SPECIFICATION FOR ADD CUSTOMER
----------------------------------------------- 
PROCEDURE ADD_CUSTOMER
(P_CUST_FIRST_NAME VARCHAR2,
 P_INITIALS varchar2,
 P_CUST_LAST_NAME VARCHAR2,
 P_CUST_GENDER VARCHAR2 DEFAULT 'F',
 P_CUST_DOB DATE,
 P_CUST_TYPE VARCHAR2 DEFAULT 'IND');

-- PROCEDURE SPECIFICATION FOR ADD CUSTOMER CONTACT 
-----------------------------------------------------
 PROCEDURE ADD_CUSTOMER_CONTACT
(P_CUST_ID  BANK_CUST_CONTACT.CUST_ID%TYPE,
 P_CUST_PHONE BANK_CUST_CONTACT.CUST_PHONE%TYPE,
 P_CONTACT_TYPE BANK_CUST_CONTACT.CONTACT_TYPE%TYPE DEFAULT 'HOME',
 P_CUST_ADDR_LINE1 BANK_CUST_CONTACT.CUST_ADDR_LINE1%TYPE,
 P_CUST_ADDR_LINE2 BANK_CUST_CONTACT.CUST_ADDR_LINE2%TYPE,
 P_CUST_CITY BANK_CUST_CONTACT.CUST_CITY%TYPE,
 P_CUST_STATE BANK_CUST_CONTACT.CUST_STATE%TYPE,
 P_CUST_PIN BANK_CUST_CONTACT.CUST_PIN%TYPE);

-- PROCEDURE SPECIFICATION FOR OPENING SAVINGS ACCOUNT 
-----------------------------------------------------------------
 PROCEDURE ADD_SAVINGBANK_ACCOUNT (
  P_PRIMARY_CUST_ID BANK_SB_ACCOUNT.PRIMARY_CUST_ID%TYPE,
  P_SECONDARY_CUST_ID BANK_SB_ACCOUNT.SECONDARY_CUST_ID%TYPE DEFAULT NULL,
  P_CURR_BAL_AMT BANK_SB_ACCOUNT.CURR_BAL_AMT%TYPE,
  P_ACC_STATUS BANK_SB_ACCOUNT.ACC_STATUS%TYPE DEFAULT 'Active',
  P_START_DATE BANK_SB_ACCOUNT.START_DATE%TYPE DEFAULT SYSDATE,
  P_END_DATE BANK_SB_ACCOUNT.END_DATE%TYPE DEFAULT NULL
);

--  PROCEDURE SPECIFICATION DEPOSIT IN THE SAVINGS BANK ACCOUNT
--------------------------------------------------------------------
PROCEDURE SAVINGBANK_DEPOSIT (P_TRANS_ACC_NO BANK_TRANSACTION.TRANS_ACC_NO%TYPE,
                         P_TRANS_DESC BANK_TRANSACTION.TRANS_DESC%TYPE,
                         P_TRANS_AMT BANK_TRANSACTION.TRANS_AMT%TYPE);
                         
--  PROCEDURE SPECIFICATION WITHDRAW IN THE SAVINGS BANK ACCOUNT 
----------------------------------------------------------------------- 
                       
PROCEDURE SAVINGBANK_WITHDRAW (P_TRANS_ACC_NO BANK_TRANSACTION.TRANS_ACC_NO%TYPE,
                          P_TRANS_DESC BANK_TRANSACTION.TRANS_DESC%TYPE,
                          P_TRANS_AMT BANK_TRANSACTION.TRANS_AMT%TYPE);


-- PROCEDURE SPECIFICATION FOR DELETE CUSTOMER BY USING CUSTOMER ID OR NAME
------------------------------------------------------------------------------
 
 PROCEDURE DEL_CUSTOMER(P_BANK_CUST_ID BANK_CUST.CUST_ID%TYPE);
 PROCEDURE DEL_CUSTOMER(P_CUST_FIRST_NAME BANK_CUST.CUST_FIRST_NAME%TYPE);
 

EXCE1 EXCEPTION;
EXCE2 EXCEPTION;
EXCE3 EXCEPTION;
EXCE4 EXCEPTION;
END CITI_BANK;